title:                      
description: ""
theme: jekyll-theme-slate

# Required for project sites so links resolve correctly:
url: "https://humanoid-motion-studios.github.io"
baseurl: ""

# Controls the order of tabs in the top header (left → right)

